class TransactionStrings {
  static const _values = <String, Map<String, String>>{
    'en': {
      'transaction': 'Transaction',
      'state': 'State',
      'transaction_truth_note': 'This screen shows the authoritative backend transaction state. The app does not maintain an independent transaction status.',
      'shipment_title': 'Pickup & Delivery Tracking',
      'authoritative_state': 'Authoritative transaction state',
      'shipment_truth_note': 'Shipment milestones are shown only when the backend provides verified pickup, transit, delivery, weighment, or evidence events. This screen does not infer completed milestones from static UI steps.',
      'agreement_title': 'Transaction Agreement',
      'pickup_point': 'Pickup point',
      'final_weighing_point': 'Final weighing point',
      'allowed_tolerance': 'Allowed tolerance %',
      'price_basis': 'Price basis',
      'transport_responsibility': 'Transport responsibility',
      'dispute_rule': 'Dispute rule',
      'create_agreement': 'Create Agreement',
      'confirm_agreement': 'Confirm Agreement',
      'farmer_confirmed_waiting': 'Farmer confirmed agreement. Waiting for buyer confirmation if not yet complete.',
      'farmer_confirmation_recorded': 'Farmer confirmation recorded',
    },
    'te': {
      'transaction': 'లావాదేవీ',
      'state': 'స్థితి',
      'transaction_truth_note': 'ఈ తెర బ్యాక్‌ఎండ్‌లోని అధికారిక లావాదేవీ స్థితినే చూపిస్తుంది. యాప్ స్వతంత్ర లావాదేవీ స్థితిని నిర్వహించదు.',
      'shipment_title': 'పికప్ & డెలివరీ ట్రాకింగ్',
      'authoritative_state': 'అధికారిక లావాదేవీ స్థితి',
      'shipment_truth_note': 'బ్యాక్‌ఎండ్ ధృవీకరించిన పికప్, ప్రయాణం, డెలివరీ, బరువు లేదా ఆధార సంఘటనలు ఇచ్చినప్పుడు మాత్రమే మైలురాళ్లు చూపబడతాయి. స్థిర UI దశల ఆధారంగా యాప్ పూర్తి అయినట్లు ఊహించదు.',
      'agreement_title': 'లావాదేవీ ఒప్పందం',
      'pickup_point': 'పికప్ స్థలం',
      'final_weighing_point': 'చివరి బరువు స్థలం',
      'allowed_tolerance': 'అనుమతించిన తేడా %',
      'price_basis': 'ధర ఆధారం',
      'transport_responsibility': 'రవాణా బాధ్యత',
      'dispute_rule': 'వివాద నియమం',
      'create_agreement': 'ఒప్పందం సృష్టించండి',
      'confirm_agreement': 'ఒప్పందాన్ని నిర్ధారించండి',
      'farmer_confirmed_waiting': 'రైతు ఒప్పందాన్ని నిర్ధారించారు. కొనుగోలుదారు ఇంకా నిర్ధారించకపోతే వేచి ఉంది.',
      'farmer_confirmation_recorded': 'రైతు నిర్ధారణ నమోదైంది',
    },
    'hi': {
      'transaction': 'लेनदेन',
      'state': 'स्थिति',
      'transaction_truth_note': 'यह स्क्रीन बैकएंड की आधिकारिक लेनदेन स्थिति दिखाती है। ऐप अलग लेनदेन स्थिति नहीं रखता।',
      'shipment_title': 'पिकअप और डिलीवरी ट्रैकिंग',
      'authoritative_state': 'आधिकारिक लेनदेन स्थिति',
      'shipment_truth_note': 'माइलस्टोन तभी दिखेंगे जब बैकएंड सत्यापित पिकअप, ट्रांजिट, डिलीवरी, वजन या साक्ष्य इवेंट दे। ऐप स्थिर UI चरणों से पूर्णता नहीं मानता।',
      'agreement_title': 'लेनदेन समझौता',
      'pickup_point': 'पिकअप स्थान',
      'final_weighing_point': 'अंतिम वजन स्थान',
      'allowed_tolerance': 'अनुमत अंतर %',
      'price_basis': 'मूल्य आधार',
      'transport_responsibility': 'परिवहन जिम्मेदारी',
      'dispute_rule': 'विवाद नियम',
      'create_agreement': 'समझौता बनाएँ',
      'confirm_agreement': 'समझौता पुष्टि करें',
      'farmer_confirmed_waiting': 'किसान ने समझौते की पुष्टि की। खरीदार की पुष्टि बाकी हो तो प्रतीक्षा जारी है।',
      'farmer_confirmation_recorded': 'किसान की पुष्टि दर्ज हुई',
    },
    'mr': {
      'transaction': 'व्यवहार',
      'state': 'स्थिती',
      'transaction_truth_note': 'ही स्क्रीन बॅकएंडमधील अधिकृत व्यवहार स्थिती दाखवते. अॅप स्वतंत्र व्यवहार स्थिती ठेवत नाही.',
      'shipment_title': 'पिकअप आणि डिलिव्हरी ट्रॅकिंग',
      'authoritative_state': 'अधिकृत व्यवहार स्थिती',
      'shipment_truth_note': 'बॅकएंड सत्यापित पिकअप, प्रवास, डिलिव्हरी, वजन किंवा पुरावा घटना दिल्यावरच टप्पे दाखवले जातील.',
      'agreement_title': 'व्यवहार करार',
      'pickup_point': 'पिकअप ठिकाण',
      'final_weighing_point': 'अंतिम वजन ठिकाण',
      'allowed_tolerance': 'मान्य फरक %',
      'price_basis': 'किंमत आधार',
      'transport_responsibility': 'वाहतूक जबाबदारी',
      'dispute_rule': 'वाद नियम',
      'create_agreement': 'करार तयार करा',
      'confirm_agreement': 'करार निश्चित करा',
      'farmer_confirmed_waiting': 'शेतकऱ्याने करार निश्चित केला. खरेदीदाराची पुष्टी बाकी असल्यास प्रतीक्षा सुरू आहे.',
      'farmer_confirmation_recorded': 'शेतकरी पुष्टी नोंदली',
    },
    'ta': {
      'transaction': 'பரிவர்த்தனை',
      'state': 'நிலை',
      'transaction_truth_note': 'இந்த திரை பின்தளத்தின் அதிகாரப்பூர்வ பரிவர்த்தனை நிலையையே காட்டுகிறது. செயலி தனி நிலையை பராமரிக்காது.',
      'shipment_title': 'எடுப்பு & விநியோக கண்காணிப்பு',
      'authoritative_state': 'அதிகாரப்பூர்வ பரிவர்த்தனை நிலை',
      'shipment_truth_note': 'பின்தளம் சரிபார்க்கப்பட்ட எடுப்பு, போக்குவரத்து, விநியோகம், எடை அல்லது ஆதார நிகழ்வுகளை வழங்கும் போது மட்டுமே மைல்கற்கள் காட்டப்படும்.',
      'agreement_title': 'பரிவர்த்தனை ஒப்பந்தம்',
      'pickup_point': 'எடுப்பு இடம்',
      'final_weighing_point': 'இறுதி எடை இடம்',
      'allowed_tolerance': 'அனுமதிக்கப்பட்ட வேறுபாடு %',
      'price_basis': 'விலை அடிப்படை',
      'transport_responsibility': 'போக்குவரத்து பொறுப்பு',
      'dispute_rule': 'தகராறு விதி',
      'create_agreement': 'ஒப்பந்தம் உருவாக்கவும்',
      'confirm_agreement': 'ஒப்பந்தத்தை உறுதிப்படுத்தவும்',
      'farmer_confirmed_waiting': 'விவசாயி ஒப்பந்தத்தை உறுதிப்படுத்தினார். வாங்குபவர் உறுதி செய்யவில்லை என்றால் காத்திருக்கிறது.',
      'farmer_confirmation_recorded': 'விவசாயி உறுதி பதிவு செய்யப்பட்டது',
    },
    'ml': {
      'transaction': 'ഇടപാട്',
      'state': 'സ്ഥിതി',
      'transaction_truth_note': 'ഈ സ്ക്രീൻ ബാക്ക്എൻഡിലെ ഔദ്യോഗിക ഇടപാട് നില മാത്രമാണ് കാണിക്കുന്നത്. ആപ്പ് വേറെ ഇടപാട് നില സൂക്ഷിക്കില്ല.',
      'shipment_title': 'പിക്കപ്പ് & ഡെലിവറി ട്രാക്കിംഗ്',
      'authoritative_state': 'ഔദ്യോഗിക ഇടപാട് നില',
      'shipment_truth_note': 'ബാക്ക്എൻഡ് സ്ഥിരീകരിച്ച പിക്കപ്പ്, യാത്ര, ഡെലിവറി, തൂക്കം അല്ലെങ്കിൽ തെളിവ് ഇവന്റുകൾ നൽകുമ്പോൾ മാത്രമേ ഘട്ടങ്ങൾ കാണിക്കൂ.',
      'agreement_title': 'ഇടപാട് കരാർ',
      'pickup_point': 'പിക്കപ്പ് സ്ഥലം',
      'final_weighing_point': 'അവസാന തൂക്കസ്ഥലം',
      'allowed_tolerance': 'അനുവദിച്ച വ്യത്യാസം %',
      'price_basis': 'വിലയുടെ അടിസ്ഥാനം',
      'transport_responsibility': 'ഗതാഗത ഉത്തരവാദിത്തം',
      'dispute_rule': 'തർക്ക നിയമം',
      'create_agreement': 'കരാർ സൃഷ്ടിക്കുക',
      'confirm_agreement': 'കരാർ സ്ഥിരീകരിക്കുക',
      'farmer_confirmed_waiting': 'കർഷകൻ കരാർ സ്ഥിരീകരിച്ചു. വാങ്ങുന്നയാളുടെ സ്ഥിരീകരണം ബാക്കിയാണെങ്കിൽ കാത്തിരിക്കുന്നു.',
      'farmer_confirmation_recorded': 'കർഷക സ്ഥിരീകരണം രേഖപ്പെടുത്തി',
    },
  };

  static String tr(String language, String key) =>
      _values[language]?[key] ?? _values['en']![key] ?? key;
}
