class TransactionStateStrings {
  static const supportedStates = {
    'DRAFT',
    'AWAITING_VERIFICATION',
    'VERIFIED',
    'PUBLISHED',
    'BIDDING',
    'OFFER_ACCEPTED',
    'AGREEMENT_PENDING',
    'AGREEMENT_LOCKED',
    'FUNDS_SECURED',
    'PICKUP_SCHEDULED',
    'PICKED_UP',
    'IN_TRANSIT',
    'DELIVERED',
    'DELIVERY_VERIFICATION',
    'TOLERANCE_CHECK',
    'SETTLED',
    'DISPUTED',
    'RESOLVED',
    'CLOSED',
  };

  static const _values = <String, Map<String, String>>{
    'en': {
      'DRAFT': 'Draft',
      'AWAITING_VERIFICATION': 'Awaiting verification',
      'VERIFIED': 'Verified',
      'PUBLISHED': 'Published',
      'BIDDING': 'Bidding open',
      'OFFER_ACCEPTED': 'Offer accepted',
      'AGREEMENT_PENDING': 'Agreement pending',
      'AGREEMENT_LOCKED': 'Agreement locked',
      'FUNDS_SECURED': 'Funds secured',
      'PICKUP_SCHEDULED': 'Pickup scheduled',
      'PICKED_UP': 'Picked up',
      'IN_TRANSIT': 'In transit',
      'DELIVERED': 'Delivered',
      'DELIVERY_VERIFICATION': 'Delivery verification',
      'TOLERANCE_CHECK': 'Tolerance check',
      'SETTLED': 'Settled',
      'DISPUTED': 'Disputed',
      'RESOLVED': 'Resolved',
      'CLOSED': 'Closed',
    },
    'te': {
      'DRAFT': 'ముసాయిదా',
      'AWAITING_VERIFICATION': 'ధృవీకరణ కోసం వేచి ఉంది',
      'VERIFIED': 'ధృవీకరించబడింది',
      'PUBLISHED': 'ప్రచురించబడింది',
      'BIDDING': 'బిడ్డింగ్ కొనసాగుతోంది',
      'OFFER_ACCEPTED': 'ఆఫర్ అంగీకరించబడింది',
      'AGREEMENT_PENDING': 'ఒప్పందం పెండింగ్‌లో ఉంది',
      'AGREEMENT_LOCKED': 'ఒప్పందం లాక్ చేయబడింది',
      'FUNDS_SECURED': 'నిధులు భద్రపరచబడ్డాయి',
      'PICKUP_SCHEDULED': 'పికప్ షెడ్యూల్ చేయబడింది',
      'PICKED_UP': 'పికప్ పూర్తైంది',
      'IN_TRANSIT': 'రవాణాలో ఉంది',
      'DELIVERED': 'డెలివరీ పూర్తైంది',
      'DELIVERY_VERIFICATION': 'డెలివరీ ధృవీకరణ',
      'TOLERANCE_CHECK': 'తేడా పరిమితి తనిఖీ',
      'SETTLED': 'సెటిల్ అయింది',
      'DISPUTED': 'వివాదంలో ఉంది',
      'RESOLVED': 'పరిష్కరించబడింది',
      'CLOSED': 'ముగిసింది',
    },
    'hi': {
      'DRAFT': 'मसौदा',
      'AWAITING_VERIFICATION': 'सत्यापन की प्रतीक्षा',
      'VERIFIED': 'सत्यापित',
      'PUBLISHED': 'प्रकाशित',
      'BIDDING': 'बोली जारी है',
      'OFFER_ACCEPTED': 'ऑफर स्वीकार हुआ',
      'AGREEMENT_PENDING': 'समझौता लंबित',
      'AGREEMENT_LOCKED': 'समझौता लॉक हुआ',
      'FUNDS_SECURED': 'राशि सुरक्षित',
      'PICKUP_SCHEDULED': 'पिकअप निर्धारित',
      'PICKED_UP': 'पिकअप पूरा',
      'IN_TRANSIT': 'परिवहन में',
      'DELIVERED': 'डिलीवर हुआ',
      'DELIVERY_VERIFICATION': 'डिलीवरी सत्यापन',
      'TOLERANCE_CHECK': 'सहनशीलता जांच',
      'SETTLED': 'निपटान पूरा',
      'DISPUTED': 'विवादित',
      'RESOLVED': 'समाधान हुआ',
      'CLOSED': 'बंद',
    },
    'mr': {
      'DRAFT': 'मसुदा',
      'AWAITING_VERIFICATION': 'पडताळणीची प्रतीक्षा',
      'VERIFIED': 'पडताळलेले',
      'PUBLISHED': 'प्रकाशित',
      'BIDDING': 'बोली सुरू आहे',
      'OFFER_ACCEPTED': 'ऑफर स्वीकारली',
      'AGREEMENT_PENDING': 'करार प्रलंबित',
      'AGREEMENT_LOCKED': 'करार लॉक झाला',
      'FUNDS_SECURED': 'रक्कम सुरक्षित',
      'PICKUP_SCHEDULED': 'पिकअप नियोजित',
      'PICKED_UP': 'पिकअप पूर्ण',
      'IN_TRANSIT': 'वाहतुकीत',
      'DELIVERED': 'डिलिव्हरी पूर्ण',
      'DELIVERY_VERIFICATION': 'डिलिव्हरी पडताळणी',
      'TOLERANCE_CHECK': 'फरक मर्यादा तपासणी',
      'SETTLED': 'सेटल झाले',
      'DISPUTED': 'वादग्रस्त',
      'RESOLVED': 'निकाल झाला',
      'CLOSED': 'बंद',
    },
    'ta': {
      'DRAFT': 'வரைவு',
      'AWAITING_VERIFICATION': 'சரிபார்ப்புக்காக காத்திருக்கிறது',
      'VERIFIED': 'சரிபார்க்கப்பட்டது',
      'PUBLISHED': 'வெளியிடப்பட்டது',
      'BIDDING': 'ஏலம் நடைபெறுகிறது',
      'OFFER_ACCEPTED': 'சலுகை ஏற்கப்பட்டது',
      'AGREEMENT_PENDING': 'ஒப்பந்தம் நிலுவையில்',
      'AGREEMENT_LOCKED': 'ஒப்பந்தம் பூட்டப்பட்டது',
      'FUNDS_SECURED': 'நிதி பாதுகாக்கப்பட்டது',
      'PICKUP_SCHEDULED': 'எடுப்பு திட்டமிடப்பட்டது',
      'PICKED_UP': 'எடுப்பு முடிந்தது',
      'IN_TRANSIT': 'போக்குவரத்தில்',
      'DELIVERED': 'விநியோகம் முடிந்தது',
      'DELIVERY_VERIFICATION': 'விநியோக சரிபார்ப்பு',
      'TOLERANCE_CHECK': 'வேறுபாடு வரம்பு சரிபார்ப்பு',
      'SETTLED': 'தீர்வு முடிந்தது',
      'DISPUTED': 'தகராறில் உள்ளது',
      'RESOLVED': 'தீர்க்கப்பட்டது',
      'CLOSED': 'மூடப்பட்டது',
    },
    'ml': {
      'DRAFT': 'കരട്',
      'AWAITING_VERIFICATION': 'സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു',
      'VERIFIED': 'സ്ഥിരീകരിച്ചു',
      'PUBLISHED': 'പ്രസിദ്ധീകരിച്ചു',
      'BIDDING': 'ബിഡ്ഡിംഗ് തുടരുന്നു',
      'OFFER_ACCEPTED': 'ഓഫർ അംഗീകരിച്ചു',
      'AGREEMENT_PENDING': 'കരാർ ബാക്കിയുണ്ട്',
      'AGREEMENT_LOCKED': 'കരാർ ലോക്ക് ചെയ്തു',
      'FUNDS_SECURED': 'തുക സുരക്ഷിതമാക്കി',
      'PICKUP_SCHEDULED': 'പിക്കപ്പ് നിശ്ചയിച്ചു',
      'PICKED_UP': 'പിക്കപ്പ് പൂർത്തിയായി',
      'IN_TRANSIT': 'ഗതാഗതത്തിലാണ്',
      'DELIVERED': 'ഡെലിവറി പൂർത്തിയായി',
      'DELIVERY_VERIFICATION': 'ഡെലിവറി സ്ഥിരീകരണം',
      'TOLERANCE_CHECK': 'വ്യത്യാസ പരിധി പരിശോധന',
      'SETTLED': 'സെറ്റിൽ ചെയ്തു',
      'DISPUTED': 'തർക്കത്തിലാണ്',
      'RESOLVED': 'പരിഹരിച്ചു',
      'CLOSED': 'അടച്ചു',
    },
  };

  static String label(String language, String state) {
    return _values[language]?[state] ?? _values['en']?[state] ?? state;
  }

  static bool hasCompleteLanguage(String language) {
    final values = _values[language];
    return values != null && supportedStates.every(values.containsKey);
  }
}
