class AppStrings {
  static const supportedLanguages = ['te', 'hi', 'en', 'mr', 'ta', 'ml'];

  static const values = <String, Map<String, String>>{
    'en': {
      'mobile_verification': 'Mobile Verification',
      'enter_otp': 'Enter OTP',
      'choose_language': 'Choose Language',
      'farmer_details': 'Farmer Details',
      'kyc_verification': 'KYC Verification',
      'payout_setup': 'Payout Setup',
      'review_registration': 'Review Registration',
      'mobile_number': 'Mobile number',
      'otp': 'OTP',
      'full_name': 'Full name',
      'village': 'Village',
      'mandal': 'Mandal',
      'district': 'District',
      'aadhaar_number': '12-digit Aadhaar number',
      'aadhaar_note': 'Aadhaar verification will be handled by the selected compliant KYC provider. Raw Aadhaar is not stored in the core backend.',
      'upi_bank': 'UPI ID or Bank Account',
      'payout_note': 'Payout details are collected only during new registration.',
      'review_note': 'Review your information before submitting registration.',
      'continue': 'Continue',
      'submit_registration': 'Submit Registration',
      'namaste': 'Namaste',
      'farmer_dashboard': 'Farmer Dashboard',
      'live_listings': 'LIVE LISTINGS',
      'offers': 'OFFERS',
      'settled': 'SETTLED',
      'add_goat_lot': 'Add Goat / Create Lot',
      'add_goat_lot_desc': 'Add an individual goat or a multi-goat lot.',
      'your_listings': 'Your Listings',
      'your_listings_desc': 'View live and historical listings.',
      'create_verified_listing': 'Create Verified Listing',
      'create_verified_listing_desc': 'Requires a verified and acknowledged weighment.',
      'individual_goat': 'Individual Goat',
      'multiple_goats_lot': 'Multiple Goats / Lot',
      'breed': 'Breed',
      'quantity': 'Quantity',
      'male': 'Male',
      'female': 'Female',
      'unknown': 'Unknown',
      'create_lot': 'Create Lot',
      'add_individual_goat': 'Add Individual Goat',
      'price_listing_rules': 'Price & Listing Rules',
      'goat_id_lot_id': 'Goat ID / Lot ID',
      'verified_weight': 'Verified weight',
      'market_recommendation': 'Average market price recommendation',
      'no_recommendation': 'No recommendation available',
      'use': 'Use',
      'your_price': 'Your price ₹ / kg',
      'estimated_listing_value': 'Estimated listing value',
      'ack_verified_weighment': 'I acknowledge the verified weighment',
      'publish_verified_listing': 'Publish Verified Listing',
      'farmer_acknowledgement': 'Farmer Acknowledgement',
      'verified_weighment': 'Verified weighment',
      'review_weighment_note': 'Review the operator-created verified weight, Scale ID, centre and evidence before acknowledging.',
      'i_acknowledge': 'I acknowledge',
      'ack_confirm_note': 'I confirm the verified weighment shown to me.',
      'reject_reweigh': 'Reject weight and request reweigh',
      'reweigh_required': 'Weight rejected · fresh reweigh required',
      'set_price_listing': 'Set Price & Listing Rules',
      'buyer_offers': 'Buyer Offers',
      'no_offers': 'No offers yet.',
      'total': 'Total',
      'server_sequence': 'Server sequence',
      'accept': 'Accept',
      'open_dispute': 'Open Dispute',
      'weight_difference': 'Weight difference',
      'wrong_animal': 'Wrong animal',
      'quantity_mismatch': 'Quantity mismatch',
      'other': 'Other',
      'disputed_amount': 'Disputed amount in paise',
      'dispute_note': 'Only the disputed amount should be held where supported. Evidence and controlled reweighing determine resolution.',
      'settlement': 'Settlement',
      'final_settlement': 'Final settlement',
      'gross': 'Gross',
      'adjustment': 'Adjustment',
      'platform_fee': 'Platform fee',
      'load_complete_settlement': 'Load / Complete Settlement',
      'connection_error': 'Unable to connect to PashuSetu. Please check the backend connection and try again.',
    },
    'te': {
      'mobile_verification': 'మొబైల్ ధృవీకరణ',
      'enter_otp': 'OTP నమోదు చేయండి',
      'choose_language': 'భాషను ఎంచుకోండి',
      'farmer_details': 'రైతు వివరాలు',
      'kyc_verification': 'KYC ధృవీకరణ',
      'payout_setup': 'చెల్లింపు వివరాలు',
      'review_registration': 'నమోదును సమీక్షించండి',
      'mobile_number': 'మొబైల్ నంబర్',
      'otp': 'OTP',
      'full_name': 'పూర్తి పేరు',
      'village': 'గ్రామం',
      'mandal': 'మండలం',
      'district': 'జిల్లా',
      'aadhaar_number': '12 అంకెల ఆధార్ నంబర్',
      'aadhaar_note': 'ఆధార్ ధృవీకరణను ఎంపిక చేసిన అనుగుణ KYC సేవ ద్వారా నిర్వహిస్తాము. అసలు ఆధార్ నంబర్‌ను ప్రధాన బ్యాక్‌ఎండ్‌లో నిల్వ చేయము.',
      'upi_bank': 'UPI ఐడి లేదా బ్యాంక్ ఖాతా',
      'payout_note': 'చెల్లింపు వివరాలు కొత్త నమోదు సమయంలో మాత్రమే అడుగుతాము.',
      'review_note': 'నమోదు సమర్పించే ముందు మీ వివరాలను సమీక్షించండి.',
      'continue': 'కొనసాగించండి',
      'submit_registration': 'నమోదు సమర్పించండి',
      'namaste': 'నమస్తే',
      'farmer_dashboard': 'రైతు డ్యాష్‌బోర్డ్',
      'live_listings': 'ప్రస్తుత జాబితాలు',
      'offers': 'ఆఫర్లు',
      'settled': 'సెటిల్ అయినవి',
      'add_goat_lot': 'మేకను జోడించండి / లాట్ సృష్టించండి',
      'add_goat_lot_desc': 'ఒక మేకను లేదా అనేక మేకల లాట్‌ను జోడించండి.',
      'your_listings': 'మీ జాబితాలు',
      'your_listings_desc': 'ప్రస్తుత మరియు పాత జాబితాలను చూడండి.',
      'create_verified_listing': 'ధృవీకరించిన జాబితా సృష్టించండి',
      'create_verified_listing_desc': 'ధృవీకరించిన మరియు రైతు అంగీకరించిన బరువు అవసరం.',
      'individual_goat': 'ఒక్క మేక',
      'multiple_goats_lot': 'అనేక మేకలు / లాట్',
      'breed': 'జాతి',
      'quantity': 'సంఖ్య',
      'male': 'మగ',
      'female': 'ఆడ',
      'unknown': 'తెలియదు',
      'create_lot': 'లాట్ సృష్టించండి',
      'add_individual_goat': 'ఒక్క మేకను జోడించండి',
      'price_listing_rules': 'ధర & జాబితా నియమాలు',
      'goat_id_lot_id': 'మేక ID / లాట్ ID',
      'verified_weight': 'ధృవీకరించిన బరువు',
      'market_recommendation': 'సగటు మార్కెట్ ధర సూచన',
      'no_recommendation': 'ధర సూచన అందుబాటులో లేదు',
      'use': 'వాడండి',
      'your_price': 'మీ ధర ₹ / కిలో',
      'estimated_listing_value': 'అంచనా మొత్తం విలువ',
      'ack_verified_weighment': 'ధృవీకరించిన బరువును నేను అంగీకరిస్తున్నాను',
      'publish_verified_listing': 'ధృవీకరించిన జాబితాను ప్రచురించండి',
      'farmer_acknowledgement': 'రైతు అంగీకారం',
      'verified_weighment': 'ధృవీకరించిన బరువు',
      'review_weighment_note': 'అంగీకరించే ముందు ఆపరేటర్ నమోదు చేసిన బరువు, స్కేల్ ID, కేంద్రం మరియు ఆధారాలను పరిశీలించండి.',
      'i_acknowledge': 'నేను అంగీకరిస్తున్నాను',
      'ack_confirm_note': 'నాకు చూపించిన ధృవీకరించిన బరువును నేను నిర్ధారిస్తున్నాను.',
      'set_price_listing': 'ధర & జాబితా నియమాలు నిర్ణయించండి',
      'buyer_offers': 'కొనుగోలుదారుల ఆఫర్లు',
      'no_offers': 'ఇంకా ఆఫర్లు లేవు.',
      'total': 'మొత్తం',
      'server_sequence': 'సర్వర్ క్రమ సంఖ్య',
      'accept': 'అంగీకరించండి',
      'open_dispute': 'వివాదం నమోదు చేయండి',
      'weight_difference': 'బరువు తేడా',
      'wrong_animal': 'తప్పు జంతువు',
      'quantity_mismatch': 'సంఖ్య సరిపోలలేదు',
      'other': 'ఇతర',
      'disputed_amount': 'వివాదంలో ఉన్న మొత్తం (పైసల్లో)',
      'dispute_note': 'అవసరమైన సందర్భంలో వివాదంలో ఉన్న మొత్తాన్ని మాత్రమే నిలిపివేయాలి. ఆధారాలు మరియు నియంత్రిత మళ్లీ బరువు ద్వారా పరిష్కారం నిర్ణయించబడుతుంది.',
      'settlement': 'సెటిల్‌మెంట్',
      'final_settlement': 'చివరి సెటిల్‌మెంట్',
      'gross': 'మొత్తం',
      'adjustment': 'సర్దుబాటు',
      'platform_fee': 'ప్లాట్‌ఫాం ఫీజు',
      'load_complete_settlement': 'సెటిల్‌మెంట్‌ను లోడ్ / పూర్తి చేయండి',
      'connection_error': 'PashuSetu సర్వర్‌కు కనెక్ట్ కాలేకపోయాం. బ్యాక్‌ఎండ్ కనెక్షన్‌ను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
    },
  };

  static String tr(String language, String key) {
    return values[language]?[key] ?? values['en']?[key] ?? key;
  }
}
