class AppStrings {
  static const supportedLanguages = ['te', 'hi', 'en', 'mr', 'ta', 'ml'];

  static const values = <String, Map<String, String>>{
    'en': {
      'mobile_verification': 'Mobile Verification',
      'enter_otp': 'Enter OTP',
      'choose_language': 'Choose Language',
      'farmer_details': 'Farmer Details',
      'kyc_verification': 'KYC Verification',
      'payout_setup': 'Payout Setup',
      'review_registration': 'Review Registration',
      'mobile_number': 'Mobile number',
      'otp': 'OTP',
      'full_name': 'Full name',
      'village': 'Village',
      'mandal': 'Mandal',
      'district': 'District',
      'aadhaar_number': '12-digit Aadhaar number',
      'aadhaar_note': 'Aadhaar verification will be handled by the selected compliant KYC provider. Raw Aadhaar is not stored in the core backend.',
      'upi_bank': 'UPI ID or Bank Account',
      'payout_note': 'Payout details are collected only during new registration.',
      'review_note': 'Review your information before submitting registration.',
      'continue': 'Continue',
      'submit_registration': 'Submit Registration',
      'namaste': 'Namaste',
      'farmer_dashboard': 'Farmer Dashboard',
      'live_listings': 'LIVE LISTINGS',
      'offers': 'OFFERS',
      'settled': 'SETTLED',
      'add_goat_lot': 'Add Goat / Create Lot',
      'add_goat_lot_desc': 'Add an individual goat or a multi-goat lot.',
      'your_listings': 'Your Listings',
      'your_listings_desc': 'View live and historical listings.',
      'create_verified_listing': 'Create Verified Listing',
      'create_verified_listing_desc': 'Requires a verified and acknowledged weighment.',
      'individual_goat': 'Individual Goat',
      'multiple_goats_lot': 'Multiple Goats / Lot',
      'breed': 'Breed',
      'quantity': 'Quantity',
      'male': 'Male',
      'female': 'Female',
      'unknown': 'Unknown',
      'create_lot': 'Create Lot',
      'add_individual_goat': 'Add Individual Goat',
      'price_listing_rules': 'Price & Listing Rules',
      'goat_id_lot_id': 'Goat ID / Lot ID',
      'verified_weight': 'Verified weight',
      'market_recommendation': 'Reference Price',
      'no_recommendation': 'No reference price available',
      'reference_source': 'Source / evidence',
      'reference_effective_date': 'Effective date',
      'use': 'Use',
      'your_price': 'Your price ₹ / kg',
      'estimated_listing_value': 'Estimated listing value',
      'ack_verified_weighment': 'I acknowledge the verified weighment',
      'publish_verified_listing': 'Publish Verified Listing',
      'farmer_acknowledgement': 'Farmer Acknowledgement',
      'verified_weighment': 'Verified weighment',
      'review_weighment_note': 'Review the operator-created verified weight, Scale ID, centre and evidence before acknowledging.',
      'i_acknowledge': 'I acknowledge',
      'ack_confirm_note': 'I confirm the verified weighment shown to me.',
      'set_price_listing': 'Set Price & Listing Rules',
      'buyer_offers': 'Buyer Offers',
      'no_offers': 'No offers yet.',
      'total': 'Total',
      'server_sequence': 'Server sequence',
      'accept': 'Accept',
      'open_dispute': 'Open Dispute',
      'weight_difference': 'Weight difference',
      'wrong_animal': 'Wrong animal',
      'quantity_mismatch': 'Quantity mismatch',
      'other': 'Other',
      'disputed_amount': 'Disputed amount in paise',
      'dispute_note': 'Only the disputed amount should be held where supported. Evidence and controlled reweighing determine resolution.',
      'settlement': 'Settlement',
      'final_settlement': 'Final settlement',
      'gross': 'Gross',
      'adjustment': 'Adjustment',
      'platform_fee': 'Platform fee',
      'load_complete_settlement': 'Load / Complete Settlement',
      'connection_error': 'Unable to connect to Setugo. Please check the backend connection and try again.',
    },
    'te': {
      'mobile_verification': 'మొబైల్ ధృవీకరణ',
      'enter_otp': 'OTP నమోదు చేయండి',
      'choose_language': 'భాషను ఎంచుకోండి',
      'farmer_details': 'రైతు వివరాలు',
      'kyc_verification': 'KYC ధృవీకరణ',
      'payout_setup': 'చెల్లింపు వివరాలు',
      'review_registration': 'నమోదును సమీక్షించండి',
      'mobile_number': 'మొబైల్ నంబర్',
      'otp': 'OTP',
      'full_name': 'పూర్తి పేరు',
      'village': 'గ్రామం',
      'mandal': 'మండలం',
      'district': 'జిల్లా',
      'aadhaar_number': '12 అంకెల ఆధార్ నంబర్',
      'aadhaar_note': 'ఆధార్ ధృవీకరణను ఎంపిక చేసిన అనుగుణ KYC సేవ ద్వారా నిర్వహిస్తాము. అసలు ఆధార్ నంబర్‌ను ప్రధాన బ్యాక్‌ఎండ్‌లో నిల్వ చేయము.',
      'upi_bank': 'UPI ఐడి లేదా బ్యాంక్ ఖాతా',
      'payout_note': 'చెల్లింపు వివరాలు కొత్త నమోదు సమయంలో మాత్రమే అడుగుతాము.',
      'review_note': 'నమోదు సమర్పించే ముందు మీ వివరాలను సమీక్షించండి.',
      'continue': 'కొనసాగించండి',
      'submit_registration': 'నమోదు సమర్పించండి',
      'namaste': 'నమస్తే',
      'farmer_dashboard': 'రైతు డ్యాష్‌బోర్డ్',
      'live_listings': 'ప్రస్తుత జాబితాలు',
      'offers': 'ఆఫర్లు',
      'settled': 'సెటిల్ అయినవి',
      'add_goat_lot': 'మేకను జోడించండి / లాట్ సృష్టించండి',
      'add_goat_lot_desc': 'ఒక మేకను లేదా అనేక మేకల లాట్‌ను జోడించండి.',
      'your_listings': 'మీ జాబితాలు',
      'your_listings_desc': 'ప్రస్తుత మరియు పాత జాబితాలను చూడండి.',
      'create_verified_listing': 'ధృవీకరించిన జాబితా సృష్టించండి',
      'create_verified_listing_desc': 'ధృవీకరించిన మరియు రైతు అంగీకరించిన బరువు అవసరం.',
      'individual_goat': 'ఒక్క మేక',
      'multiple_goats_lot': 'అనేక మేకలు / లాట్',
      'breed': 'జాతి',
      'quantity': 'సంఖ్య',
      'male': 'మగ',
      'female': 'ఆడ',
      'unknown': 'తెలియదు',
      'create_lot': 'లాట్ సృష్టించండి',
      'add_individual_goat': 'ఒక్క మేకను జోడించండి',
      'price_listing_rules': 'ధర & జాబితా నియమాలు',
      'goat_id_lot_id': 'మేక ID / లాట్ ID',
      'verified_weight': 'ధృవీకరించిన బరువు',
      'market_recommendation': 'సూచన ధర',
      'no_recommendation': 'సూచన ధర అందుబాటులో లేదు',
      'reference_source': 'మూలం / ఆధారం',
      'reference_effective_date': 'అమలులోకి వచ్చిన తేదీ',
      'use': 'వాడండి',
      'your_price': 'మీ ధర ₹ / కిలో',
      'estimated_listing_value': 'అంచనా మొత్తం విలువ',
      'ack_verified_weighment': 'ధృవీకరించిన బరువును నేను అంగీకరిస్తున్నాను',
      'publish_verified_listing': 'ధృవీకరించిన జాబితాను ప్రచురించండి',
      'farmer_acknowledgement': 'రైతు అంగీకారం',
      'verified_weighment': 'ధృవీకరించిన బరువు',
      'review_weighment_note': 'అంగీకరించే ముందు ఆపరేటర్ నమోదు చేసిన బరువు, స్కేల్ ID, కేంద్రం మరియు ఆధారాలను పరిశీలించండి.',
      'i_acknowledge': 'నేను అంగీకరిస్తున్నాను',
      'ack_confirm_note': 'నాకు చూపించిన ధృవీకరించిన బరువును నేను నిర్ధారిస్తున్నాను.',
      'set_price_listing': 'ధర & జాబితా నియమాలు నిర్ణయించండి',
      'buyer_offers': 'కొనుగోలుదారుల ఆఫర్లు',
      'no_offers': 'ఇంకా ఆఫర్లు లేవు.',
      'total': 'మొత్తం',
      'server_sequence': 'సర్వర్ క్రమ సంఖ్య',
      'accept': 'అంగీకరించండి',
      'open_dispute': 'వివాదం నమోదు చేయండి',
      'weight_difference': 'బరువు తేడా',
      'wrong_animal': 'తప్పు జంతువు',
      'quantity_mismatch': 'సంఖ్య సరిపోలలేదు',
      'other': 'ఇతర',
      'disputed_amount': 'వివాదంలో ఉన్న మొత్తం (పైసల్లో)',
      'dispute_note': 'అవసరమైన సందర్భంలో వివాదంలో ఉన్న మొత్తాన్ని మాత్రమే నిలిపివేయాలి. ఆధారాలు మరియు నియంత్రిత మళ్లీ బరువు ద్వారా పరిష్కారం నిర్ణయించబడుతుంది.',
      'settlement': 'సెటిల్‌మెంట్',
      'final_settlement': 'చివరి సెటిల్‌మెంట్',
      'gross': 'మొత్తం',
      'adjustment': 'సర్దుబాటు',
      'platform_fee': 'ప్లాట్‌ఫాం ఫీజు',
      'load_complete_settlement': 'సెటిల్‌మెంట్‌ను లోడ్ / పూర్తి చేయండి',
      'connection_error': 'Setugo సర్వర్‌కు కనెక్ట్ కాలేకపోయాం. బ్యాక్‌ఎండ్ కనెక్షన్‌ను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
    },
    'hi': {
      'mobile_verification': 'मोबाइल सत्यापन',
      'enter_otp': 'OTP दर्ज करें',
      'choose_language': 'भाषा चुनें',
      'farmer_details': 'किसान विवरण',
      'kyc_verification': 'KYC सत्यापन',
      'payout_setup': 'भुगतान विवरण',
      'review_registration': 'पंजीकरण की समीक्षा करें',
      'mobile_number': 'मोबाइल नंबर',
      'otp': 'OTP',
      'full_name': 'पूरा नाम',
      'village': 'गांव',
      'mandal': 'मंडल',
      'district': 'जिला',
      'aadhaar_number': '12 अंकों का आधार नंबर',
      'aadhaar_note': 'आधार सत्यापन चुने गए अनुपालनशील KYC प्रदाता द्वारा किया जाएगा। कच्चा आधार नंबर मुख्य बैकएंड में संग्रहीत नहीं किया जाता।',
      'upi_bank': 'UPI ID या बैंक खाता',
      'payout_note': 'भुगतान विवरण केवल नए पंजीकरण के दौरान लिए जाते हैं।',
      'review_note': 'पंजीकरण जमा करने से पहले अपनी जानकारी की समीक्षा करें।',
      'continue': 'जारी रखें',
      'submit_registration': 'पंजीकरण जमा करें',
      'namaste': 'नमस्ते',
      'farmer_dashboard': 'किसान डैशबोर्ड',
      'live_listings': 'सक्रिय लिस्टिंग',
      'offers': 'ऑफर',
      'settled': 'निपटाए गए',
      'add_goat_lot': 'बकरी जोड़ें / लॉट बनाएं',
      'add_goat_lot_desc': 'एक बकरी या कई बकरियों का लॉट जोड़ें।',
      'your_listings': 'आपकी लिस्टिंग',
      'your_listings_desc': 'सक्रिय और पुरानी लिस्टिंग देखें।',
      'create_verified_listing': 'सत्यापित लिस्टिंग बनाएं',
      'create_verified_listing_desc': 'सत्यापित और स्वीकार किया गया वजन आवश्यक है।',
      'individual_goat': 'एक बकरी',
      'multiple_goats_lot': 'कई बकरियां / लॉट',
      'breed': 'नस्ल',
      'quantity': 'संख्या',
      'male': 'नर',
      'female': 'मादा',
      'unknown': 'अज्ञात',
      'create_lot': 'लॉट बनाएं',
      'add_individual_goat': 'एक बकरी जोड़ें',
      'price_listing_rules': 'मूल्य और लिस्टिंग नियम',
      'goat_id_lot_id': 'बकरी ID / लॉट ID',
      'verified_weight': 'सत्यापित वजन',
      'market_recommendation': 'संदर्भ मूल्य',
      'no_recommendation': 'संदर्भ मूल्य उपलब्ध नहीं है',
      'reference_source': 'स्रोत / प्रमाण',
      'reference_effective_date': 'प्रभावी तिथि',
      'use': 'उपयोग करें',
      'your_price': 'आपका मूल्य ₹ / किग्रा',
      'estimated_listing_value': 'अनुमानित लिस्टिंग मूल्य',
      'ack_verified_weighment': 'मैं सत्यापित वजन को स्वीकार करता/करती हूं',
      'publish_verified_listing': 'सत्यापित लिस्टिंग प्रकाशित करें',
      'farmer_acknowledgement': 'किसान की स्वीकृति',
      'verified_weighment': 'सत्यापित वजन',
      'review_weighment_note': 'स्वीकार करने से पहले ऑपरेटर द्वारा दर्ज वजन, स्केल ID, केंद्र और प्रमाण की समीक्षा करें।',
      'i_acknowledge': 'मैं स्वीकार करता/करती हूं',
      'ack_confirm_note': 'मैं मुझे दिखाए गए सत्यापित वजन की पुष्टि करता/करती हूं।',
      'set_price_listing': 'मूल्य और लिस्टिंग नियम तय करें',
      'buyer_offers': 'खरीदार ऑफर',
      'no_offers': 'अभी कोई ऑफर नहीं है।',
      'total': 'कुल',
      'server_sequence': 'सर्वर क्रम',
      'accept': 'स्वीकार करें',
      'open_dispute': 'विवाद दर्ज करें',
      'weight_difference': 'वजन में अंतर',
      'wrong_animal': 'गलत पशु',
      'quantity_mismatch': 'संख्या मेल नहीं खाती',
      'other': 'अन्य',
      'disputed_amount': 'विवादित राशि (पैसे में)',
      'dispute_note': 'जहां समर्थित हो, केवल विवादित राशि रोकी जानी चाहिए। प्रमाण और नियंत्रित पुनः वजन से समाधान तय होगा।',
      'settlement': 'निपटान',
      'final_settlement': 'अंतिम निपटान',
      'gross': 'सकल',
      'adjustment': 'समायोजन',
      'platform_fee': 'प्लेटफॉर्म शुल्क',
      'load_complete_settlement': 'निपटान लोड / पूरा करें',
      'connection_error': 'Setugo से कनेक्ट नहीं हो सका। बैकएंड कनेक्शन जांचें और फिर कोशिश करें।',
    },
    'mr': {
      'mobile_verification': 'मोबाइल पडताळणी',
      'enter_otp': 'OTP टाका',
      'choose_language': 'भाषा निवडा',
      'farmer_details': 'शेतकरी तपशील',
      'kyc_verification': 'KYC पडताळणी',
      'payout_setup': 'पेमेंट तपशील',
      'review_registration': 'नोंदणी तपासा',
      'mobile_number': 'मोबाइल क्रमांक',
      'otp': 'OTP',
      'full_name': 'पूर्ण नाव',
      'village': 'गाव',
      'mandal': 'मंडळ',
      'district': 'जिल्हा',
      'aadhaar_number': '12 अंकी आधार क्रमांक',
      'aadhaar_note': 'आधार पडताळणी निवडलेल्या अनुरूप KYC प्रदात्यामार्फत केली जाईल. मूळ आधार क्रमांक मुख्य बॅकएंडमध्ये साठवला जात नाही.',
      'upi_bank': 'UPI ID किंवा बँक खाते',
      'payout_note': 'पेमेंट तपशील फक्त नवीन नोंदणीदरम्यान घेतले जातात.',
      'review_note': 'नोंदणी सबमिट करण्यापूर्वी माहिती तपासा.',
      'continue': 'पुढे जा',
      'submit_registration': 'नोंदणी सबमिट करा',
      'namaste': 'नमस्कार',
      'farmer_dashboard': 'शेतकरी डॅशबोर्ड',
      'live_listings': 'सक्रिय लिस्टिंग',
      'offers': 'ऑफर',
      'settled': 'निपटलेले',
      'add_goat_lot': 'शेळी जोडा / लॉट तयार करा',
      'add_goat_lot_desc': 'एक शेळी किंवा अनेक शेळ्यांचा लॉट जोडा.',
      'your_listings': 'तुमच्या लिस्टिंग',
      'your_listings_desc': 'सक्रिय आणि जुने लिस्टिंग पहा.',
      'create_verified_listing': 'पडताळलेली लिस्टिंग तयार करा',
      'create_verified_listing_desc': 'पडताळलेले आणि मान्य केलेले वजन आवश्यक आहे.',
      'individual_goat': 'एक शेळी',
      'multiple_goats_lot': 'अनेक शेळ्या / लॉट',
      'breed': 'जात',
      'quantity': 'संख्या',
      'male': 'नर',
      'female': 'मादी',
      'unknown': 'माहित नाही',
      'create_lot': 'लॉट तयार करा',
      'add_individual_goat': 'एक शेळी जोडा',
      'price_listing_rules': 'किंमत आणि लिस्टिंग नियम',
      'goat_id_lot_id': 'शेळी ID / लॉट ID',
      'verified_weight': 'पडताळलेले वजन',
      'market_recommendation': 'संदर्भ किंमत',
      'no_recommendation': 'संदर्भ किंमत उपलब्ध नाही',
      'reference_source': 'स्रोत / पुरावा',
      'reference_effective_date': 'लागू दिनांक',
      'use': 'वापरा',
      'your_price': 'तुमची किंमत ₹ / किलो',
      'estimated_listing_value': 'अंदाजे लिस्टिंग मूल्य',
      'ack_verified_weighment': 'मी पडताळलेले वजन मान्य करतो/करते',
      'publish_verified_listing': 'पडताळलेली लिस्टिंग प्रकाशित करा',
      'farmer_acknowledgement': 'शेतकरी मान्यता',
      'verified_weighment': 'पडताळलेले वजन',
      'review_weighment_note': 'मान्य करण्यापूर्वी ऑपरेटरने नोंदवलेले वजन, स्केल ID, केंद्र आणि पुरावा तपासा.',
      'i_acknowledge': 'मी मान्य करतो/करते',
      'ack_confirm_note': 'मला दाखवलेले पडताळलेले वजन मी पुष्टी करतो/करते.',
      'set_price_listing': 'किंमत आणि लिस्टिंग नियम ठरवा',
      'buyer_offers': 'खरेदीदार ऑफर',
      'no_offers': 'अजून ऑफर नाहीत.',
      'total': 'एकूण',
      'server_sequence': 'सर्व्हर क्रम',
      'accept': 'स्वीकारा',
      'open_dispute': 'वाद नोंदवा',
      'weight_difference': 'वजनातील फरक',
      'wrong_animal': 'चुकीचा प्राणी',
      'quantity_mismatch': 'संख्या जुळत नाही',
      'other': 'इतर',
      'disputed_amount': 'वादग्रस्त रक्कम (पैशात)',
      'dispute_note': 'जिथे समर्थित असेल तिथे फक्त वादग्रस्त रक्कम रोखली पाहिजे. पुरावा आणि नियंत्रित पुनर्वजनातून निकाल ठरेल.',
      'settlement': 'सेटलमेंट',
      'final_settlement': 'अंतिम सेटलमेंट',
      'gross': 'एकूण',
      'adjustment': 'समायोजन',
      'platform_fee': 'प्लॅटफॉर्म शुल्क',
      'load_complete_settlement': 'सेटलमेंट लोड / पूर्ण करा',
      'connection_error': 'Setugo शी कनेक्ट होता आले नाही. बॅकएंड कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
    },
    'ta': {
      'mobile_verification': 'மொபைல் சரிபார்ப்பு',
      'enter_otp': 'OTP ஐ உள்ளிடவும்',
      'choose_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'farmer_details': 'விவசாயி விவரங்கள்',
      'kyc_verification': 'KYC சரிபார்ப்பு',
      'payout_setup': 'பணம் பெறும் விவரங்கள்',
      'review_registration': 'பதிவை மதிப்பாய்வு செய்யவும்',
      'mobile_number': 'மொபைல் எண்',
      'otp': 'OTP',
      'full_name': 'முழுப் பெயர்',
      'village': 'கிராமம்',
      'mandal': 'மண்டல்',
      'district': 'மாவட்டம்',
      'aadhaar_number': '12 இலக்க ஆதார் எண்',
      'aadhaar_note': 'ஆதார் சரிபார்ப்பு தேர்ந்தெடுக்கப்பட்ட இணக்கமான KYC வழங்குநர் மூலம் மேற்கொள்ளப்படும். மூல ஆதார் எண் பிரதான பின்தளத்தில் சேமிக்கப்படாது.',
      'upi_bank': 'UPI ID அல்லது வங்கி கணக்கு',
      'payout_note': 'பணம் பெறும் விவரங்கள் புதிய பதிவின் போது மட்டும் சேகரிக்கப்படும்.',
      'review_note': 'பதிவை சமர்ப்பிக்கும் முன் உங்கள் தகவலை மதிப்பாய்வு செய்யவும்.',
      'continue': 'தொடரவும்',
      'submit_registration': 'பதிவை சமர்ப்பிக்கவும்',
      'namaste': 'வணக்கம்',
      'farmer_dashboard': 'விவசாயி டாஷ்போர்டு',
      'live_listings': 'செயலில் உள்ள பட்டியல்கள்',
      'offers': 'சலுகைகள்',
      'settled': 'தீர்வு செய்யப்பட்டவை',
      'add_goat_lot': 'ஆட்டைச் சேர்க்கவும் / லாட் உருவாக்கவும்',
      'add_goat_lot_desc': 'ஒரு ஆடு அல்லது பல ஆடுகளைக் கொண்ட லாட்டைச் சேர்க்கவும்.',
      'your_listings': 'உங்கள் பட்டியல்கள்',
      'your_listings_desc': 'செயலில் உள்ள மற்றும் பழைய பட்டியல்களைப் பார்க்கவும்.',
      'create_verified_listing': 'சரிபார்க்கப்பட்ட பட்டியலை உருவாக்கவும்',
      'create_verified_listing_desc': 'சரிபார்க்கப்பட்ட மற்றும் ஏற்றுக்கொள்ளப்பட்ட எடை தேவை.',
      'individual_goat': 'ஒரு ஆடு',
      'multiple_goats_lot': 'பல ஆடுகள் / லாட்',
      'breed': 'இனம்',
      'quantity': 'எண்ணிக்கை',
      'male': 'ஆண்',
      'female': 'பெண்',
      'unknown': 'தெரியாது',
      'create_lot': 'லாட் உருவாக்கவும்',
      'add_individual_goat': 'ஒரு ஆட்டைச் சேர்க்கவும்',
      'price_listing_rules': 'விலை மற்றும் பட்டியல் விதிகள்',
      'goat_id_lot_id': 'ஆடு ID / லாட் ID',
      'verified_weight': 'சரிபார்க்கப்பட்ட எடை',
      'market_recommendation': 'குறிப்பு விலை',
      'no_recommendation': 'குறிப்பு விலை கிடைக்கவில்லை',
      'reference_source': 'மூலம் / ஆதாரம்',
      'reference_effective_date': 'அமல்படும் தேதி',
      'use': 'பயன்படுத்து',
      'your_price': 'உங்கள் விலை ₹ / கிலோ',
      'estimated_listing_value': 'மதிப்பிடப்பட்ட பட்டியல் மதிப்பு',
      'ack_verified_weighment': 'சரிபார்க்கப்பட்ட எடையை நான் ஏற்கிறேன்',
      'publish_verified_listing': 'சரிபார்க்கப்பட்ட பட்டியலை வெளியிடவும்',
      'farmer_acknowledgement': 'விவசாயி ஒப்புதல்',
      'verified_weighment': 'சரிபார்க்கப்பட்ட எடை',
      'review_weighment_note': 'ஏற்கும் முன் ஆபரேட்டர் பதிவு செய்த எடை, Scale ID, மையம் மற்றும் ஆதாரத்தை மதிப்பாய்வு செய்யவும்.',
      'i_acknowledge': 'நான் ஏற்கிறேன்',
      'ack_confirm_note': 'எனக்குக் காட்டப்பட்ட சரிபார்க்கப்பட்ட எடையை உறுதிப்படுத்துகிறேன்.',
      'set_price_listing': 'விலை மற்றும் பட்டியல் விதிகளை அமைக்கவும்',
      'buyer_offers': 'வாங்குபவர் சலுகைகள்',
      'no_offers': 'இன்னும் சலுகைகள் இல்லை.',
      'total': 'மொத்தம்',
      'server_sequence': 'சர்வர் வரிசை',
      'accept': 'ஏற்கவும்',
      'open_dispute': 'தகராறு பதிவு செய்யவும்',
      'weight_difference': 'எடை வேறுபாடு',
      'wrong_animal': 'தவறான விலங்கு',
      'quantity_mismatch': 'எண்ணிக்கை பொருந்தவில்லை',
      'other': 'மற்றவை',
      'disputed_amount': 'தகராறு தொகை (பைசாவில்)',
      'dispute_note': 'ஆதரிக்கப்பட்டால் தகராறு செய்யப்பட்ட தொகையை மட்டும் நிறுத்த வேண்டும். ஆதாரம் மற்றும் கட்டுப்படுத்தப்பட்ட மறுஎடை தீர்வை நிர்ணயிக்கும்.',
      'settlement': 'தீர்வு',
      'final_settlement': 'இறுதி தீர்வு',
      'gross': 'மொத்தம்',
      'adjustment': 'சரிசெய்தல்',
      'platform_fee': 'தள கட்டணம்',
      'load_complete_settlement': 'தீர்வை ஏற்றவும் / முடிக்கவும்',
      'connection_error': 'Setugo உடன் இணைக்க முடியவில்லை. பின்தள இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    },
    'ml': {
      'mobile_verification': 'മൊബൈൽ സ്ഥിരീകരണം',
      'enter_otp': 'OTP നൽകുക',
      'choose_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'farmer_details': 'കർഷക വിവരങ്ങൾ',
      'kyc_verification': 'KYC സ്ഥിരീകരണം',
      'payout_setup': 'പണം ലഭിക്കുന്ന വിവരങ്ങൾ',
      'review_registration': 'രജിസ്ട്രേഷൻ പരിശോധിക്കുക',
      'mobile_number': 'മൊബൈൽ നമ്പർ',
      'otp': 'OTP',
      'full_name': 'പൂർണ്ണ പേര്',
      'village': 'ഗ്രാമം',
      'mandal': 'മണ്ഡലം',
      'district': 'ജില്ല',
      'aadhaar_number': '12 അക്ക ആധാർ നമ്പർ',
      'aadhaar_note': 'ആധാർ സ്ഥിരീകരണം തിരഞ്ഞെടുത്ത അനുസൃത KYC സേവനദാതാവിലൂടെ നടത്തും. അസൽ ആധാർ നമ്പർ പ്രധാന ബാക്ക്എൻഡിൽ സംഭരിക്കില്ല.',
      'upi_bank': 'UPI ID അല്ലെങ്കിൽ ബാങ്ക് അക്കൗണ്ട്',
      'payout_note': 'പണം ലഭിക്കുന്ന വിവരങ്ങൾ പുതിയ രജിസ്ട്രേഷനിൽ മാത്രം ശേഖരിക്കും.',
      'review_note': 'രജിസ്ട്രേഷൻ സമർപ്പിക്കുന്നതിന് മുമ്പ് നിങ്ങളുടെ വിവരങ്ങൾ പരിശോധിക്കുക.',
      'continue': 'തുടരുക',
      'submit_registration': 'രജിസ്ട്രേഷൻ സമർപ്പിക്കുക',
      'namaste': 'നമസ്കാരം',
      'farmer_dashboard': 'കർഷക ഡാഷ്ബോർഡ്',
      'live_listings': 'സജീവ ലിസ്റ്റിംഗുകൾ',
      'offers': 'ഓഫറുകൾ',
      'settled': 'തീർപ്പാക്കിയവ',
      'add_goat_lot': 'ആടിനെ ചേർക്കുക / ലോട്ട് സൃഷ്ടിക്കുക',
      'add_goat_lot_desc': 'ഒരു ആടിനെയോ നിരവധി ആടുകളുടെ ലോട്ടിനെയോ ചേർക്കുക.',
      'your_listings': 'നിങ്ങളുടെ ലിസ്റ്റിംഗുകൾ',
      'your_listings_desc': 'സജീവവും പഴയതുമായ ലിസ്റ്റിംഗുകൾ കാണുക.',
      'create_verified_listing': 'സ്ഥിരീകരിച്ച ലിസ്റ്റിംഗ് സൃഷ്ടിക്കുക',
      'create_verified_listing_desc': 'സ്ഥിരീകരിച്ചും അംഗീകരിച്ചും ഉള്ള ഭാരം ആവശ്യമാണ്.',
      'individual_goat': 'ഒരു ആട്',
      'multiple_goats_lot': 'നിരവധി ആടുകൾ / ലോട്ട്',
      'breed': 'ഇനം',
      'quantity': 'എണ്ണം',
      'male': 'ആൺ',
      'female': 'പെൺ',
      'unknown': 'അറിയില്ല',
      'create_lot': 'ലോട്ട് സൃഷ്ടിക്കുക',
      'add_individual_goat': 'ഒരു ആടിനെ ചേർക്കുക',
      'price_listing_rules': 'വിലയും ലിസ്റ്റിംഗ് നിയമങ്ങളും',
      'goat_id_lot_id': 'ആട് ID / ലോട്ട് ID',
      'verified_weight': 'സ്ഥിരീകരിച്ച ഭാരം',
      'market_recommendation': 'റഫറൻസ് വില',
      'no_recommendation': 'റഫറൻസ് വില ലഭ്യമല്ല',
      'reference_source': 'ഉറവിടം / തെളിവ്',
      'reference_effective_date': 'പ്രാബല്യ തീയതി',
      'use': 'ഉപയോഗിക്കുക',
      'your_price': 'നിങ്ങളുടെ വില ₹ / കിലോ',
      'estimated_listing_value': 'കണക്കാക്കിയ ലിസ്റ്റിംഗ് മൂല്യം',
      'ack_verified_weighment': 'സ്ഥിരീകരിച്ച ഭാരം ഞാൻ അംഗീകരിക്കുന്നു',
      'publish_verified_listing': 'സ്ഥിരീകരിച്ച ലിസ്റ്റിംഗ് പ്രസിദ്ധീകരിക്കുക',
      'farmer_acknowledgement': 'കർഷക അംഗീകാരം',
      'verified_weighment': 'സ്ഥിരീകരിച്ച ഭാരം',
      'review_weighment_note': 'അംഗീകരിക്കുന്നതിന് മുമ്പ് ഓപ്പറേറ്റർ രേഖപ്പെടുത്തിയ ഭാരം, Scale ID, കേന്ദ്രം, തെളിവ് എന്നിവ പരിശോധിക്കുക.',
      'i_acknowledge': 'ഞാൻ അംഗീകരിക്കുന്നു',
      'ack_confirm_note': 'എനിക്ക് കാണിച്ച സ്ഥിരീകരിച്ച ഭാരം ഞാൻ ഉറപ്പാക്കുന്നു.',
      'set_price_listing': 'വിലയും ലിസ്റ്റിംഗ് നിയമങ്ങളും നിശ്ചയിക്കുക',
      'buyer_offers': 'വാങ്ങുന്നവരുടെ ഓഫറുകൾ',
      'no_offers': 'ഇനിയും ഓഫറുകളില്ല.',
      'total': 'ആകെ',
      'server_sequence': 'സർവർ ക്രമം',
      'accept': 'അംഗീകരിക്കുക',
      'open_dispute': 'തർക്കം രേഖപ്പെടുത്തുക',
      'weight_difference': 'ഭാര വ്യത്യാസം',
      'wrong_animal': 'തെറ്റായ മൃഗം',
      'quantity_mismatch': 'എണ്ണം പൊരുത്തപ്പെടുന്നില്ല',
      'other': 'മറ്റ്',
      'disputed_amount': 'തർക്കത്തിലുള്ള തുക (പൈസയിൽ)',
      'dispute_note': 'പിന്തുണയുള്ളിടത്ത് തർക്കത്തിലുള്ള തുക മാത്രം തടഞ്ഞുവയ്ക്കണം. തെളിവും നിയന്ത്രിത പുനർഭാരവും പരിഹാരം നിർണ്ണയിക്കും.',
      'settlement': 'സെറ്റിൽമെന്റ്',
      'final_settlement': 'അന്തിമ സെറ്റിൽമെന്റ്',
      'gross': 'മൊത്തം',
      'adjustment': 'ക്രമീകരണം',
      'platform_fee': 'പ്ലാറ്റ്ഫോം ഫീസ്',
      'load_complete_settlement': 'സെറ്റിൽമെന്റ് ലോഡ് / പൂർത്തിയാക്കുക',
      'connection_error': 'Setugo-യുമായി ബന്ധപ്പെടാനായില്ല. ബാക്ക്എൻഡ് കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    },
  };

  static String tr(String language, String key) {
    return values[language]?[key] ?? values['en']?[key] ?? key;
  }
}
