class ProfileStrings {
  static const values = <String, Map<String, String>>{
    'en': {
      'title': 'My Profile',
      'farmer_id': 'Farmer ID',
      'village': 'Village',
      'mandal': 'Mandal',
      'district': 'District',
      'state': 'State',
      'kyc_status': 'KYC status',
      'payout_status': 'Payout status',
      'profile_error': 'Unable to load your profile. Please refresh and try again.',
      'not_available': 'Not available',
    },
    'te': {
      'title': 'నా ప్రొఫైల్',
      'farmer_id': 'రైతు ID',
      'village': 'గ్రామం',
      'mandal': 'మండలం',
      'district': 'జిల్లా',
      'state': 'రాష్ట్రం',
      'kyc_status': 'KYC స్థితి',
      'payout_status': 'చెల్లింపు స్థితి',
      'profile_error': 'మీ ప్రొఫైల్‌ను లోడ్ చేయలేకపోయాం. రిఫ్రెష్ చేసి మళ్లీ ప్రయత్నించండి.',
      'not_available': 'అందుబాటులో లేదు',
    },
    'hi': {
      'title': 'मेरी प्रोफ़ाइल',
      'farmer_id': 'किसान ID',
      'village': 'गांव',
      'mandal': 'मंडल',
      'district': 'जिला',
      'state': 'राज्य',
      'kyc_status': 'KYC स्थिति',
      'payout_status': 'भुगतान स्थिति',
      'profile_error': 'आपकी प्रोफ़ाइल लोड नहीं हो सकी। कृपया रीफ्रेश करके फिर प्रयास करें।',
      'not_available': 'उपलब्ध नहीं',
    },
    'mr': {
      'title': 'माझे प्रोफाइल',
      'farmer_id': 'शेतकरी ID',
      'village': 'गाव',
      'mandal': 'मंडळ',
      'district': 'जिल्हा',
      'state': 'राज्य',
      'kyc_status': 'KYC स्थिती',
      'payout_status': 'पेमेंट स्थिती',
      'profile_error': 'तुमचे प्रोफाइल लोड करता आले नाही. रिफ्रेश करून पुन्हा प्रयत्न करा.',
      'not_available': 'उपलब्ध नाही',
    },
    'ta': {
      'title': 'என் சுயவிவரம்',
      'farmer_id': 'விவசாயி ID',
      'village': 'கிராமம்',
      'mandal': 'மண்டல்',
      'district': 'மாவட்டம்',
      'state': 'மாநிலம்',
      'kyc_status': 'KYC நிலை',
      'payout_status': 'பணம் செலுத்தும் நிலை',
      'profile_error': 'உங்கள் சுயவிவரத்தை ஏற்ற முடியவில்லை. புதுப்பித்து மீண்டும் முயற்சிக்கவும்.',
      'not_available': 'கிடைக்கவில்லை',
    },
    'ml': {
      'title': 'എന്റെ പ്രൊഫൈൽ',
      'farmer_id': 'കർഷക ID',
      'village': 'ഗ്രാമം',
      'mandal': 'മണ്ഡലം',
      'district': 'ജില്ല',
      'state': 'സംസ്ഥാനം',
      'kyc_status': 'KYC സ്ഥിതി',
      'payout_status': 'പേയൗട്ട് സ്ഥിതി',
      'profile_error': 'നിങ്ങളുടെ പ്രൊഫൈൽ ലോഡ് ചെയ്യാനായില്ല. പുതുക്കി വീണ്ടും ശ്രമിക്കുക.',
      'not_available': 'ലഭ്യമല്ല',
    },
  };

  static String tr(String language, String key) {
    return values[language]?[key] ?? values['en']![key]!;
  }
}
