from enum import StrEnum


class Role(StrEnum):
    FARMER = "FARMER"
    BUYER = "BUYER"
    OPERATOR = "OPERATOR"
    ADMIN = "ADMIN"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    SUSPENDED = "SUSPENDED"


class TransactionState(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_VERIFICATION = "AWAITING_VERIFICATION"
    VERIFIED = "VERIFIED"
    PUBLISHED = "PUBLISHED"
    BIDDING = "BIDDING"
    OFFER_ACCEPTED = "OFFER_ACCEPTED"
    AGREEMENT_PENDING = "AGREEMENT_PENDING"
    AGREEMENT_LOCKED = "AGREEMENT_LOCKED"
    FUNDS_SECURED = "FUNDS_SECURED"
    PICKUP_SCHEDULED = "PICKUP_SCHEDULED"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    DELIVERY_VERIFICATION = "DELIVERY_VERIFICATION"
    TOLERANCE_CHECK = "TOLERANCE_CHECK"
    SETTLED = "SETTLED"
    DISPUTED = "DISPUTED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
